//Lista de Crops Existentes no game - seus status principais- o tempo de crescimento esta em milissegundos
const crops = [
    {name: 'Sunflower',   tempo: 60_000,      custoDaSemente: 0.01, vendaDaCrop: 0.02, estoqueDeSementes: 800, quantidade: 1, tier: 'basic',    estacao: 'Spring, Summer'},
    {name: 'Potato',      tempo: 300_000,     custoDaSemente: 0.1,  vendaDaCrop: 0.14, estoqueDeSementes: 400, quantidade: 1, tier: 'basic',    estacao: 'Summer, Autumn, Winter'},
    {name: 'Rhubarb',     tempo: 600_000,     custoDaSemente: 0.15, vendaDaCrop: 0.24, estoqueDeSementes: 400, quantidade: 1, tier: 'basic',    estacao: 'Spring'},
    {name: 'Pumpkin',     tempo: 1_800_000,   custoDaSemente: 0.2,  vendaDaCrop: 0.4,  estoqueDeSementes: 300, quantidade: 1, tier: 'basic',    estacao: 'Autumn'},
    {name: 'Zucchini',    tempo: 1_800_000,   custoDaSemente: 0.2,  vendaDaCrop: 0.4,  estoqueDeSementes: 400, quantidade: 1, tier: 'basic',    estacao: 'Summer'},
    {name: 'Carrot',      tempo: 3_600_000,   custoDaSemente: 0.5,  vendaDaCrop: 0.8,  estoqueDeSementes: 200, quantidade: 1, tier: 'medium',   estacao: 'Spring, Autumn'},
    {name: 'Yam',         tempo: 3_600_000,   custoDaSemente: 0.5,  vendaDaCrop: 0.8,  estoqueDeSementes: 180, quantidade: 1, tier: 'medium',   estacao: 'Autumn'},
    {name: 'Cabbage',     tempo: 7_200_000,   custoDaSemente: 1,    vendaDaCrop: 1.5,  estoqueDeSementes: 180, quantidade: 1, tier: 'medium',   estacao: 'Spring, Winter'},
    {name: 'Broccoli',    tempo: 7_200_000,   custoDaSemente: 1,    vendaDaCrop: 1.5,  estoqueDeSementes: 180, quantidade: 1, tier: 'medium',   estacao: 'Autumn'},
    {name: 'Soybean',     tempo: 10_800_000,  custoDaSemente: 1.5,  vendaDaCrop: 2.3,  estoqueDeSementes: 180, quantidade: 1, tier: 'medium',   estacao: 'Spring, Autumn'},
    {name: 'Pepper',      tempo: 14_400_000,  custoDaSemente: 2,    vendaDaCrop: 3,    estoqueDeSementes: 160, quantidade: 1, tier: 'medium',   estacao: 'Summer'},
    {name: 'Beetroot',    tempo: 14_400_000,  custoDaSemente: 2,    vendaDaCrop: 2.8,  estoqueDeSementes: 160, quantidade: 1, tier: 'medium',   estacao: 'Summer, Winter'},
    {name: 'Cauliflower', tempo: 28_800_000,  custoDaSemente: 3,    vendaDaCrop: 4.25, estoqueDeSementes: 160, quantidade: 1, tier: 'medium',   estacao: 'Summer, Winter'},
    {name: 'Parsnip',     tempo: 43_200_000,  custoDaSemente: 5,    vendaDaCrop: 6.5,  estoqueDeSementes: 120, quantidade: 1, tier: 'medium',   estacao: 'Winter'},
    {name: 'Eggplant',    tempo: 57_600_000,  custoDaSemente: 6,    vendaDaCrop: 8,    estoqueDeSementes: 100, quantidade: 1, tier: 'advanced', estacao: 'Summer'},
    {name: 'Corn',        tempo: 72_000_000,  custoDaSemente: 7,    vendaDaCrop: 9,    estoqueDeSementes: 100, quantidade: 1, tier: 'advanced', estacao: 'Spring'},
    {name: 'Onion',       tempo: 72_000_000,  custoDaSemente: 7,    vendaDaCrop: 10,   estoqueDeSementes: 100, quantidade: 1, tier: 'advanced', estacao: 'Winter'},
    {name: 'Turnip',      tempo: 86_400_000,  custoDaSemente: 5,    vendaDaCrop: 8,    estoqueDeSementes: 80,  quantidade: 1, tier: 'advanced', estacao: 'Winter'},
    {name: 'Radish',      tempo: 86_400_000,  custoDaSemente: 7,    vendaDaCrop: 9.5,  estoqueDeSementes: 80,  quantidade: 1, tier: 'advanced', estacao: 'Summer'},
    {name: 'Wheat',       tempo: 86_400_000,  custoDaSemente: 5,    vendaDaCrop: 7,    estoqueDeSementes: 80,  quantidade: 1, tier: 'advanced', estacao: 'Spring, Summer, Autumn, Winter'},
    {name: 'Kale',        tempo: 129_600_000, custoDaSemente: 7,    vendaDaCrop: 10,   estoqueDeSementes: 60,  quantidade: 1, tier: 'advanced', estacao: 'Spring, Winter'},
    {name: 'Artichoke',   tempo: 129_600_000, custoDaSemente: 7,    vendaDaCrop: 12,   estoqueDeSementes: 60,  quantidade: 1, tier: 'advanced', estacao: 'Autumn'},
    {name: 'Barley',      tempo: 172_800_000, custoDaSemente: 10,   vendaDaCrop: 12,   estoqueDeSementes: 60,  quantidade: 1, tier: 'advanced', estacao: 'Spring, Autumn'}
];